#!/usr/bin/env bash
# FR-44's manifest check (#893): docs/design/brand-assets.md and the brand
# surface on disk say the same thing, in BOTH directions.
#
# WHY BOTH DIRECTIONS IS THE WHOLE POINT. An inventory that is only checked
# one way is the failure this repository keeps finding: hold the manifest to
# the filesystem and a row for a deleted file goes red, which is useful; do
# only that, and the next asset somebody adds is simply absent from the
# inventory and nothing anywhere notices. That second direction is the one
# FR-44 is about, because the asset nobody wrote down is exactly the asset
# that still says the old name three renames later. So:
#
#   a row naming a path that does not exist        -> FAILED
#   a brand-surface path with no row               -> FAILED
#
# WHAT COUNTS AS THE BRAND SURFACE. Four patterns, listed below as
# `surface`, matched against tracked-plus-present-and-not-ignored paths.
# Scoped by pattern rather than by a hand-kept file list for the same reason
# the scan next door is scoped by extension: a list that has to be updated
# to notice a new file cannot notice a new file.
#
# DIRECTORY ROWS. A manifest row whose path ends in `/` accounts for
# everything beneath it, and the directory has to exist and be non-empty.
# There is exactly one in the manifest today and it carries its reason in
# the row: `docs/site/screens/` is 66 product captures regenerated by
# docs/site/tools/capture-*.mjs and gated by the site half of #893, not
# brand art anybody hand-maintains. A per-file row there would be 66 rows
# that go stale on the next recording. Everything else is named file by
# file, including all eleven `docs/design/` mockup PNGs, because a
# directory row is a hole in the second direction and the holes should be
# countable.
#
# Exit code contract:
#
#   0  every row has a file and every file has a row
#   1  at least one of those is false, and the run named which
#
# Registered in scripts/ci-local.sh beside scripts/rename/check-brand-drift.sh.
# scripts/brand/selftest.sh plants a row with no file and a file with no row
# and requires this to go red on each.
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"

manifest="docs/design/brand-assets.md"
if [ ! -f "$manifest" ]; then
  echo "check-brand-assets: FAILED: $manifest does not exist" >&2
  exit 1
fi

# The brand surface. Every vector source in the tree, every icon container,
# and the raster exports in the three directories that hold them.
surface="$(
  git ls-files --cached --others --exclude-standard -- \
    '*.svg' '*.ico' \
    'docs/assets/*.png' 'docs/site/assets/*.png' 'ui/shared/public/*.png' \
    'docs/design/*.png' 'docs/site/screens/*' | sort -u
)"

if [ -z "$surface" ]; then
  echo "check-brand-assets: FAILED: no brand asset found at all, so this check inspected nothing" >&2
  exit 1
fi

# The manifest's rows. A row is a table line whose FIRST cell is a single
# backticked path; everything else in the document -- prose, the human
# acceptance section, the construction notes, tables that are not the
# inventory -- has a first cell that is not one, and is skipped. Parsed
# this way rather than by section heading so that moving the table does not
# silently empty this check.
rows="$(
  awk -F'|' '
    /^\|/ {
      cell = $2
      gsub(/^[ \t]+|[ \t]+$/, "", cell)
      if (cell ~ /^`[^`]+`$/) {
        gsub(/`/, "", cell)
        print cell
      }
    }
  ' "$manifest" | sort -u
)"

if [ -z "$rows" ]; then
  echo "check-brand-assets: FAILED: no inventory row parsed out of $manifest, so this check inspected nothing" >&2
  exit 1
fi

report="$(
  ROWS="$rows" SURFACE="$surface" awk '
    function load(blob, set,   n, i, parts) {
      n = split(blob, parts, "\n")
      for (i = 1; i <= n; i++) if (parts[i] != "") set[parts[i]] = 1
    }
    BEGIN {
      load(ENVIRON["ROWS"], row)
      load(ENVIRON["SURFACE"], disk)

      # Direction one: a row naming nothing on disk. A row ending in `/` is
      # a directory row and is satisfied by any file beneath it.
      for (r in row) {
        if (r ~ /\/$/) {
          covered = 0
          for (d in disk) if (index(d, r) == 1) { covered = 1; break }
          if (!covered) printf "E\t  %s  (directory row, and nothing is under it)\n", r
          dirrow[r] = 1
          continue
        }
        if (!(r in disk)) printf "E\t  %s\n", r
      }

      # Direction two: a file on disk that no row accounts for.
      for (d in disk) {
        if (d in row) continue
        covered = 0
        for (r in dirrow) if (index(d, r) == 1) { covered = 1; break }
        if (!covered) printf "M\t  %s\n", d
      }

      n = 0
      for (r in row) n++
      printf "C\t%d\n", n
    }
  ' </dev/null
)"

ghosts="$(sed -n 's/^E	//p' <<<"$report" | sort)"
unlisted="$(sed -n 's/^M	//p' <<<"$report" | sort)"
row_count="$(sed -n 's/^C	//p' <<<"$report")"

status=0

if [ -n "$ghosts" ]; then
  echo "check-brand-assets: FAILED: $manifest has a row for something that is not in the tree:" >&2
  printf '%s\n' "$ghosts" >&2
  echo "check-brand-assets: either the file was deleted or renamed and the row has to follow it, or the row was written for an asset nobody produced." >&2
  status=1
fi

if [ -n "$unlisted" ]; then
  echo "check-brand-assets: FAILED: a brand asset is in the tree with no row in $manifest:" >&2
  printf '%s\n' "$unlisted" >&2
  cat >&2 <<'EOF'
check-brand-assets: this is the direction FR-44 exists for. An asset nobody
  wrote down is the asset that still depicts the old name after the rename
  is declared finished, because the only thing that would have caught it is
  somebody remembering it was there. Add a row naming the file, its declared
  sizes, the source it is exported from, and where it is embedded.
EOF
  status=1
fi

if [ "$status" -ne 0 ]; then
  exit 1
fi

surface_count="$(printf '%s\n' "$surface" | wc -l | tr -d ' ')"
echo "check-brand-assets: ok ($row_count row(s) in $manifest, $surface_count brand-surface path(s) on disk, both directions)"
